language: node_js

node_js:
  - 4.2.1

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower protractor
  - npm install
  - bower install
  - node ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update --standalone
  - node ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager start > /dev/null &
  - sleep 5

script: grunt test
